// -----------------------------------------------------------------------------
// Filename: WebhookEventTypesEum.cs
// 
// Description: The different types of web hooks that are generated by the
// MoneyMoov API.
//
// Author(s):
// Aaron Clauson (aaron@nofrixion.com)
// 
// History:
// 24 Dec 2022  Aaron Clauson    Renamed from WebHook to WebhookEventTypesEum.
// 
// License:
// MIT.
// -----------------------------------------------------------------------------

namespace NoFrixion.MoneyMoov;

public enum WebhookEventTypesEum
{
    NONE,

    PAYIN,

    PAYOUT,
}

