/*
 * Yapily API
 *
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.14.0
 * Contact: support@yapily.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace NoFrixion.MoneyMoov.Models.OpenBanking;

[DataContract(Name = "IsoBankTransactionCode")]
public partial class IsoBankTransactionCode
{
    /// <summary>
    /// Gets or Sets DomainCode
    /// </summary>
    [DataMember(Name = "domainCode", EmitDefaultValue = false)]
    public IsoCodeDetails DomainCode { get; set; } = new IsoCodeDetails();

    /// <summary>
    /// Gets or Sets FamilyCode
    /// </summary>
    [DataMember(Name = "familyCode", EmitDefaultValue = false)]
    public IsoCodeDetails FamilyCode { get; set; } = new IsoCodeDetails();

    /// <summary>
    /// Gets or Sets SubFamilyCode
    /// </summary>
    [DataMember(Name = "subFamilyCode", EmitDefaultValue = false)]
    public IsoCodeDetails SubFamilyCode { get; set; } = new IsoCodeDetails();
}
